NotelyProject/NotelyProject/urls.py
"""
Definition of urls for NotelyProject.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views


urlpatterns = [
    path('', views.home, name='home'),
    path('new-note/', views.create_note, name='create_note'),
    path('note/<int:pk>/detail/', views.note_detail, name='note_detail'),
    path('note/<int:pk>/edit/', views.edit_note, name='edit_note'),
    path('note/<int:pk>/delete/', views.delete_note, name='delete_note'),
]

NotelyProject/app/models.py
"""
Definition of models.
"""

from django.db import models
from datetime import datetime

class Note(models.Model):
    subject = models.CharField(max_length = 500)
    detail = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField()
    last_modified = models.DateTimeField()
    is_deleted = models.BooleanField()


    def create(self):
        self.created_date = datetime.now()
        self.last_modified = datetime.now()
        self.is_deleted = False
        self.save()

    def edit(self):
        self.last_modified = datetime.now()
        self.save()

    def delete(self):
        self.last_modified = datetime.now()
        self.is_deleted = True
        self.save()

NotelyProject/app/forms.py
"""
Definition of forms.
"""
from django import forms
from .models import Note


class NoteForm(forms.ModelForm):

     class Meta:
         model = Note
         fields = ("subject", "detail")
         widgets = {
            'subject': forms.TextInput(attrs={
                'class': 'form-control note-editor__subject-input'
                }),
            'detail': forms.Textarea(attrs={
                'class': 'form-control note-editor__detail-input', 
                'rows':'12',
                'cols':'20',
                }),
         }

NotelyProject/app/views.py
"""
Definition of views.
"""


from datetime import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest
from .forms import NoteForm
from .models import Note

def home(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)
    notes = Note.objects.filter(is_deleted = False)
    return render(
        request,
        'app/index.html',
        {
            'title':'My Notes',
            'year':datetime.now().year,
            'notes' : notes
        }
    )

def note_detail(request, pk):
    """Renders the note detail page."""
    assert isinstance(request, HttpRequest)
    note =  get_object_or_404(Note, pk=pk)
    return render(
        request,
        'app/note_detail.html',
        {
            'title':'Note Detail',
            'year':datetime.now().year,
            'note': note
        }
    )
  
def create_note(request):
    """Renders the create note page."""
    assert isinstance(request, HttpRequest)

    if request.method == "POST":
          form = NoteForm(request.POST)
          if form.is_valid():
              note = form.save(commit = False)             
              note.create()
              return redirect("home")
    else:
        form  = NoteForm
        return render(
            request, 
            'app/create_note.html', 
            {
                'title':'New Note',
                'year':datetime.now().year,
                'form': form
            } 
        )

def edit_note(request, pk):
    """Renders the edit note page."""
    assert isinstance(request, HttpRequest)

    note =  get_object_or_404(Note, pk=pk)

    if request.method == "POST":
          form = NoteForm(request.POST, instance = note)
          if form.is_valid():
              note = form.save(commit = False)             
              note.edit()
              return redirect("home")
    else:
        form  = NoteForm(instance = note)
        return render(
            request, 
            'app/edit_note.html', 
            {
                'title':'Edit Note',
                'year':datetime.now().year,
                'form': form,
                'id': note.id
            } 
        )

def delete_note(request, pk):
    """deletes note and return to home page."""
    assert isinstance(request, HttpRequest)

    note =  get_object_or_404(Note, pk=pk)
    note.delete()

    return redirect("home")

NotelyProject/app/templates/app/create_note.html
{% extends "app/layout.html" %}

{% block content %}

<div class="note-editor">
  <div class="panel panel-default note-editor__panel">
    <div class="panel-heading note-editor__header">
      <h1 class="panel-title note-editor__panel-title">
        <span>Create New Note</span>
      </h1>
    </div>
    <form method="POST">
      {% csrf_token %}
      <div class="panel-body note-editor__panel-body">
        {% if form.errors %}
        <p class="validation-summary-errors">Please enter a correct user name and password.</p>
        {% endif %}
        <div class="form-group">
          <label class="note-editor__input-label" for="id_subject">Subject</label>
          {{form.subject}}
        </div>
        <div class="form-group">
          <label class="note-editor__input-label" for="id_detail">Your Note</label>
          {{form.detail}}
        </div>
      </div>

      <div class="panel-footer">
        <div class="note-editor__flex-container">
          <a class="btn btn-sm note-editor__button" href="{% url 'home' %}">Cancel </a>
          <button class="btn btn-sm note-editor__button" type="submit">Save Note</button>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

NotelyProject/app/templates/app/edit_note.html
{% extends "app/layout.html" %}

{% block content %}

<div class="note-editor">
  <div class="panel panel-default note-editor__panel">
    <div class="panel-heading note-editor__header">
      <h1 class="panel-title note-editor__panel-title">
        <span>Edit Your Note</span>
      </h1>
    </div>
    <form method="POST">
      {% csrf_token %}
      <div class="panel-body note-editor__panel-body">
        <div>{{ form.errors}}</div>

        <div class="form-group">
          <label class="note-editor__input-label" for="id_subject">Subject</label>
          {{ form.subject}}
        </div>

        <div class="form-group">
          <label class="note-editor__input-label" for="id_detail">Your Note</label>
          {{ form.detail}}
        </div>
      </div>

      <div class="panel-footer">
        <div class="note-editor__flex-container">
          <a class="btn btn-sm note-editor__button" href="{% url 'note_detail' pk=id %}">Cancel </a>
          <button class="btn btn-sm note-editor__button" type="submit">Save Note</button>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

NotelyProject/app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}


<div class="index">
  {% if notes %}
      <div class="panel panel-default index__header">
        <h3 class="panel-body">
          Your Notes
        </h3>
      </div>
  
      {% for note in notes %}

      <div class="panel panel-default">
        <a href = "{% url 'note_detail' pk=note.id %}"  class="index__list-item-link">
          <div class="panel-body">
            {{note.subject}}
          </div>
        </a>
      </div>

      {% endfor %}

  {% else %}
      <div class="panel panel-default index__empty-list">
        <h3 class="panel-body">
          You don't have any notes. Click on the button below to create a note.
        </h3>
      </div>
  {% endif %}

  <div class="index__new-note-button-wrapper">
    <a href="{% url 'create_note' %}" class="index__new-note-button">New Note</a>
  </div>
</div>


{% endblock %}

NotelyProject/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ title }} - Notely</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
  <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand" style="font-size: 30px; font-weight: 500;">
        <span style="color: #008080;">Note</span><span style="color: black;">ly</span>
      </a>
    </div>
    <div class="navbar-collapse collapse navbar-right">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'create_note' %}" style="color: #008080;">New Note</a></li>
      </ul>
    </div>
  </div>
</div>

<div class="container body-content"> 
  {% block content %}{% endblock %}
  <hr/>
  <footer>
    <p>&copy; {{ year }} - Notely</p>
  </footer>
</div>

<script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
<script src="{% static 'app/scripts/bootstrap.js' %}"></script>
<script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

NotelyProject/app/templates/app/note_detail.html
{% extends "app/layout.html" %}

{% block content %}

<div class="note-detail">
  <div class="panel panel-default note-detail__panel">
    <div class="panel-heading note-detail__panel-header">
      <h1 class="panel-title note-detail__panel-title">
        {{note.subject}}
      </h1>
    </div>
    <div class="panel-body">
      <div class="note-detail__date-section">
        <div>
          <span class="note-detail__created-date-key">
            Created On:
          </span>
          <span class="note-detail__created-date-value">
            {{note.created_date}}
          </span>
        </div>
        <div>
          <span class="note-detail__modified-date-key">
            Last Modified On:
          </span>
          <span class="note-detail__modified-date-value">
            {{note.last_modified}}
          </span>
        </div>
      </div>
      <hr/>
      <div>
        {{note.detail|linebreaksbr}}
      </div>
    </div>
    <div class="panel-footer note-detail__footer">
      <div class="note-detail__flex-container">
        <div>
          <a class="note-detail__button" href="{% url 'home' %}">
            Back to List
          </a>
        </div>
        <div>
          <a class="note-detail__button" href="{% url 'edit_note' pk=note.id %}" >
            Edit Note
          </a>
        </div>
        <div>
          <a class="note-detail__button" href="{% url 'delete_note' pk=note.id %}" >
            Delete Note
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}